"""add player_private_history

Revision ID: 0c98a096e400
Revises: 5ea92c5856be
Create Date: 2026-05-19 15:02:23.747005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c98a096e400'
down_revision: Union[str, Sequence[str], None] = '5ea92c5856be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_private_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=16), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('thinking', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=False),
    sa.Column('tool_call_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_private_history_game_id'), 'player_private_history', ['game_id'], unique=False)
    op.create_index('ix_pph_game_player_seq', 'player_private_history', ['game_id', 'player_id', 'seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pph_game_player_seq', table_name='player_private_history')
    op.drop_index(op.f('ix_player_private_history_game_id'), table_name='player_private_history')
    op.drop_table('player_private_history')
    # ### end Alembic commands ###
