"""add runtime_snapshot

Revision ID: 421d5555d424
Revises: 0c98a096e400
Create Date: 2026-05-20 17:38:53.048507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421d5555d424'
down_revision: Union[str, Sequence[str], None] = '0c98a096e400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_snapshot',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('night_actions', sa.JSON(), nullable=False),
    sa.Column('eliminated_today', sa.String(length=8), nullable=True),
    sa.Column('deaths_announced_today', sa.JSON(), nullable=False),
    sa.Column('potion_states', sa.JSON(), nullable=False),
    sa.Column('last_event_seq', sa.Integer(), nullable=False),
    sa.Column('last_history_seqs', sa.JSON(), nullable=False),
    sa.Column('last_phase_name', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runtime_snapshot')
    # ### end Alembic commands ###
