"""add game tables

Revision ID: 5ea92c5856be
Revises: 5f61b5c24c48
Create Date: 2026-05-18 17:11:28.597278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea92c5856be'
down_revision: Union[str, Sequence[str], None] = '5f61b5c24c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('winner', sa.String(length=8), nullable=True),
    sa.Column('rounds_played', sa.Integer(), nullable=False),
    sa.Column('god_model', sa.String(length=64), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_game_status'), 'game', ['status'], unique=False)
    op.create_table('game_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_event_game_id'), 'game_event', ['game_id'], unique=False)
    op.create_index('ix_game_event_game_seq', 'game_event', ['game_id', 'seq'], unique=False)
    op.create_table('game_player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=8), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('alive', sa.Boolean(), nullable=False),
    sa.Column('died_at_round', sa.Integer(), nullable=True),
    sa.Column('death_cause', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_game_player_pid')
    )
    op.create_index(op.f('ix_game_player_game_id'), 'game_player', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_player_game_id'), table_name='game_player')
    op.drop_table('game_player')
    op.drop_index('ix_game_event_game_seq', table_name='game_event')
    op.drop_index(op.f('ix_game_event_game_id'), table_name='game_event')
    op.drop_table('game_event')
    op.drop_index(op.f('ix_game_status'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
